# Generated by Django 4.1.6 on 2023-03-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
